app/main/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, RadioField, SelectField
from wtforms.validators import ValidationError, DataRequired, Length
from flask_babel import _, lazy_gettext as _l
from app.models import User
from app.dbconn import conn

conn = conn()


class EditProfileForm(FlaskForm):
    fio = StringField('Фамилия Имя Отчество')
    login = StringField(_l('Login'), validators=[DataRequired()])
    about_me = TextAreaField(_l('About me'),
                             validators=[Length(min=0, max=140)])
    phone = StringField('Номер')
    avatar = StringField('Аватар')
    gender = SelectField('Пол', choices=[('Мale', 'Male'),
                                         ('Female', 'Female'),
                                         ('Transexual Male', 'Transexsual Male'),
                                         (' Transexsual Female', 'Transexsual Female'),
                                         ('Metrosexual Male', 'Metrosexual Male'),
                                         ('Metrosexual Female', 'Metrosexual Female'),
                                         ('Male, but curious what being a Female like',
                                          'Male, but curious what being a Female like'),
                                         ('Female, but curious what being a Male like',
                                          'Female, but curious what being a Male like'),
                                         ('Hermaphrodite with Predominant Male leanings',
                                          'Hermaphrodite with Predominant Male leanings'),
                                         ('Hermaphrodite with Predominant Female leanings',
                                          'Hermaphrodite with Predominant Female leanings'),
                                         ('Hermaphrodite with no strong gender leanings',
                                          'Hermaphrodite with no strong gender leanings'),
                                         ('Conjoined Twin - Male', 'Conjoined Twin - Male'),
                                         ('Conjoined Twin - Female', 'Conjoined Twin - Female'),
                                         ('Born without genitals - identify as a Male',
                                          'Born without genitals - identify as a Male'),
                                         ('Born without genitals - identify as a Female',
                                          'Born without genitals - identify as a Female'),
                                         ('Born without genitals - proud of it', 'Born without genitals - proud of it'),
                                         ('Artificial intelligence with no gender',
                                          'Artificial intelligence with no gender'),
                                         ('Artificial intelligence - identifies as Male',
                                          'Artificial intelligence -identifies as Male'),
                                         ('Artificial intelligence - identifies as Female',
                                          'Artificial intelligence -identifies as Female'),
                                         ('Household pet that walked across the keyboard - Male',
                                          'Household pet that walked across the keyboard - Male'),
                                         ('Household pet that walked across the keyboard - Female',
                                          'Household pet that walked across the keyboard - Female'),
                                         ('Household pet that walked across the keyboard - Other',
                                          'Household pet that walked across the keyboard - Other'),
                                         ('Attack helicopter', 'Attack helicopter')
                                         ])
    cursor = conn.cursor()
    submit = SubmitField(_l('Submit'))

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError(_('Please use a different username.'))


class PostForm(FlaskForm):
    post = TextAreaField(validators=[Length(min=1, max=140)])
    submit = SubmitField(_l('Отправить'))


class ComForm(FlaskForm):
    com = TextAreaField(u'Комментарий', validators=[Length(min=1, max=140)])
    submit = SubmitField(_l('Отправить'))


class EditCom(FlaskForm):
    editcom = TextAreaField(u'Редактировать', validators=[Length(min=1, max=140)])
    submit = SubmitField(_l('Отправить'))


class EditPostForm(FlaskForm):
    editpost = TextAreaField(validators=[Length(min=1, max=140)])
    submit = SubmitField(_l('Редактировать'))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_required
import random
import re
from flask_babel import _
from app.main.forms import EditProfileForm, PostForm, ComForm, EditPostForm, EditCom
from app.models import User, Post
from app.main import bp
from flask_paginate import Pagination, get_page_args
from datetime import datetime
from app.dbconn import conn
from config import Config

conn = conn()


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    cursor = conn.cursor()
    argg = request.args
    if argg and argg.get('page') is None:
        gender = argg.get('gender')
        category = argg.get('category')
        discount = argg.get('discount')
        minprice = argg.get('minprice')
        maxprice = argg.get('maxprice')
        brand = argg.get('brand')
        store = argg.get('store')
        if minprice > maxprice:
            buf = maxprice
            maxprice = minprice
            minprice = buf
        if gender:
            if gender == 'women':
                cursor.execute('SELECT * FROM ITEMS WHERE gender = %s or gender = %s', ['W','U'])
                genderY = cursor.fetchall()
            elif gender == 'men':
                cursor.execute('SELECT * FROM ITEMS WHERE gender = %s or gender = %s', ['M', 'U'])
                genderY = cursor.fetchall()
            elif gender == 'all':
                cursor.execute('SELECT * FROM ITEMS WHERE gender = %s', ['U'])
                genderY = cursor.fetchall()
    cursor.execute('select * from ITEMS')
    items = cursor.fetchall()
    ult = convert_to_list(items)
    conn.commit()
    page, per_page, offset = get_page_args(page_parameter='page', per_page_parameter='per_page')
    cursor.execute(
        'SELECT count(*) FROM ITEMS')
    total = cursor.fetchone()
    cursor.execute(
        'SELECT distinct(Brand) FROM ITEMS ORDER BY Brand ASC')
    brands = cursor.fetchall()
    cursor.execute(
        'SELECT distinct(site) FROM ITEMS ORDER BY site ASC')
    sites = cursor.fetchall()
    cursor.execute('SELECT MAX(saleprice) FROM ITEMS;')
    maxcost = cursor.fetchone()
    pagination_posts = ult[offset: offset + per_page]
    pagination = Pagination(page=page, total=total[0], record_name='items', per_page=per_page)
    chkindex = True
    return render_template('main.html', items=pagination_posts, pagination=pagination, paga=page, chkindex=chkindex, brands=brands, sites=sites, maxcost=maxcost)


@bp.route('/item/<id>', methods=['GET', 'POST'])
def item_fw(id):
    cursor = conn.cursor()
    cursor.execute('select * from ITEMS where id = %s',
                   [id])
    tkitem = cursor.fetchone()
    descr = re.sub(r'[\r]','',tkitem[12])
    description = [x for x in descr.strip().split('\n') if x]
    item = list(tkitem)
    item[10] = re.sub(r'[{}]', '', item[10]).split(',')
    full = [it.replace('737x737', '1474x1474') for it in item[10]]
    review = [it.replace('737x737', '120x120') for it in item[10]]
    conn.commit()
    cursor.execute('SELECT * FROM ITEMS WHERE TYPEITEM=%s AND NOT ID=%s', [item[9], id])
    types = cursor.fetchall()
    type = convert_to_list(types)
    cursor.execute('SELECT count(*) FROM ITEMS WHERE TYPEITEM=%s AND NOT ID=%s', [item[9], id])
    skilko = cursor.fetchone()
    if skilko[0] < 4:
        relateditems = type
    elif skilko[0] >= 4:
        relateditems = random.sample(type, 4)
    kolvo = len(item[10])
    return render_template('submainitem.html', title=item[5], item=item, kolvo=kolvo, review=review, full=full,
                           related=relateditems, description=description)



def convert_to_list(type):
    ult = [list(item) for item in type]
    for ul in ult:
        try:
            index = int(ult.index(ul))
            ult[index][10] = re.sub(r'[{}]', '', ul[10]).split(',')
        except:
            continue
    return ult


@bp.route('/shop/<gender>/<type>', methods=['GET', 'POST'])
def shopw(gender,type):
    cursor = conn.cursor()
    if gender == 'women':
        gend = 'W'
    elif gender == 'men':
        gend = 'M'
    if type:
        cursor.execute('select * from ITEMS WHERE (gender = %s or gender = %s) and typeitem = %s', ['U', gend, type])
    else:
        cursor.execute('select * from ITEMS WHERE gender = %s or gender = %s', ['U', gend])
    items = cursor.fetchall()
    ult = convert_to_list(items)
    conn.commit()
    page, per_page, offset = get_page_args(page_parameter='page', per_page_parameter='per_page')
    if type:
        cursor.execute(
            'SELECT count(*) FROM ITEMS WHERE (gender = %s or gender = %s) and typeitem = %s', ['U',gend,type])
    else:
        cursor.execute('select count(*) from ITEMS WHERE gender = %s or gender = %s', ['U', gend])
    total = cursor.fetchone()
    pagination_posts = ult[offset: offset + per_page]
    pagination = Pagination(page=page, total=total[0], record_name='items', per_page=per_page)
    return render_template('main.html', items=pagination_posts, pagination=pagination, paga=page)


@bp.route('/shop/<gender>', methods=['GET', 'POST'])
def shopg(gender):
    if gender == 'women':
        gend = 'W'
    elif gender == 'men':
        gend = 'M'
    cursor = conn.cursor()
    cursor.execute('select * from ITEMS WHERE gender = %s or gender = %s', ['U', gend])
    items = cursor.fetchall()
    ult = convert_to_list(items)
    conn.commit()
    page, per_page, offset = get_page_args(page_parameter='page', per_page_parameter='per_page')
    cursor.execute(
        'SELECT count(*) FROM ITEMS WHERE gender = %s or gender = %s', ['U', gend])
    total = cursor.fetchone()
    pagination_posts = ult[offset: offset + per_page]
    pagination = Pagination(page=page, total=total[0], record_name='items', per_page=per_page)
    return render_template('main.html', items=pagination_posts, pagination=pagination, paga=page)


@bp.route('/search', methods=['GET', 'POST'])
def search():
    arg = request.args['q']
    if arg == '':
        return redirect(url_for('main.index'))
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM ITEMS WHERE to_tsvector(BRAND) || to_tsvector(nameitem) || to_tsvector(typeitem) @@ plainto_tsquery(%s)', [arg])
    items = cursor.fetchall()
    ult = convert_to_list(items)
    conn.commit()
    page, per_page, offset = get_page_args(page_parameter='page', per_page_parameter='per_page')
    cursor.execute(
        'SELECT count(*) FROM ITEMS WHERE to_tsvector(BRAND) || to_tsvector(nameitem) || to_tsvector(typeitem) @@ plainto_tsquery(%s)', [arg])
    total = cursor.fetchone()
    pagination_posts = ult[offset: offset + per_page]
    pagination = Pagination(page=page, total=total[0], record_name='items', per_page=per_page)
    checksrch = True
    return render_template('main.html', items=pagination_posts, pagination=pagination, paga=page, arg=arg, checksrch=checksrch )


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.login)
    cursor = conn.cursor()
    vuz = form.SelVUZ.data
    cursor.execute('select idFack,nameFack from facultet where idvuz = %s', [vuz])
    fack = cursor.fetchall()
    conn.commit()
    kolvofack = len(fack)
    form.SelFack.choices = fack
    Fack = form.SelFack.data
    cursor.execute('select idKafedra,nameKafedra from kafedra where idfack = %s', [Fack])
    kaf = cursor.fetchall()
    conn.commit()
    form.SelKaf.choices = kaf
    Kaf = form.SelKaf.data
    if form.validate_on_submit():
        cursor = conn.cursor()
        current_user.fio = form.fio.data
        current_user.phone = form.phone.data
        current_user.gender = form.gender.data
        current_user.about_me = form.about_me.data
        current_user.avatar = form.avatar.data
        cursor.execute(
            'update Uzer set fio = %s, login = %s, phone = %s, gender = %s, about_me = %s, avatar = %s where login = %s',
            [current_user.fio, form.login.data, current_user.phone, current_user.gender, current_user.about_me,
             current_user.avatar, current_user.login])
        conn.commit()
        cursor.execute('SELECT iduser FROM VO WHERE iduser = %s', [current_user.id])
        iduser = cursor.fetchone()
        conn.commit()
        if iduser is None:
            cursor.execute('INSERT INTO VO(iduser,idvuz,idfack,idkafedra) VALUES(%s,%s,%s,%s)',
                           [current_user.id, vuz, Fack, Kaf])
            conn.commit()
        else:
            cursor.execute('UPDATE VO SET idvuz = %s,idfack = %s, idkafedra = %s WHERE iduser = %s',
                           [vuz, Fack, Kaf, current_user.id])
            conn.commit()
        current_user.login = form.login.data
        flash(_('Your changes have been saved.'))
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.fio.data = current_user.fio
        form.login.data = current_user.login
        form.phone.data = current_user.phone
        form.gender.data = current_user.gender
        form.about_me.data = current_user.about_me
        form.avatar.data = current_user.avatar
        cursor.execute('SELECT idvuz,idfack,idkafedra from VO where iduser = %s', [current_user.id])
        numb = cursor.fetchone()
        if numb is not None:
            form.SelVUZ.data = numb[0]
            form.SelFack.data = numb[1]
            form.SelKaf.data = numb[2]
    return render_template('edit_profile.html', title=_('Edit Profile'),
                           form=form, vuz=vuz, kolvofack=kolvofack, Kaf=Kaf, fack=fack)


@bp.route('/follow/<id>')
@login_required
def follow(id):
    cursor = conn.cursor()
    cursor.execute('select * from Uzer where iduser = %s',
                   [id])
    user = cursor.fetchone()
    conn.commit()
    if user is None:
        flash(_('User %(username)s not found.', username=user[5]))
        return redirect(url_for('main.index'))

app/templates/_com.html
<table class="table table-hover">
        <tr>
            <td width="70px">
                <a href="{{ url_for('main.user', id = com[16]) }}">
                    <img src="{{ com[20] }}" width="40" height="40"/>
                </a>
            </td>
            <td>
                {% set user_link %}
                    <span class="user_popup">
                        <a href="{{ url_for('main.user', id=com[16]) }}">
                            {{ com[12] }}
                        </a>
                    </span>
                {% endset %}
                {{ _('%(username)s прокомментировал',
                    username=user_link) }}
                <br>
                <span id="post{{ com[7] }}">{{ com[5] }}</span>
                <br>
                <p>{{ _('%(when)s', when=moment(com[6]).fromNow()) }}
                {% if com[17] == current_user.login or current_user.login == logen or current_user.login == 'tehno-09@mail.ru' %}
                    <a href="{{ url_for('main.deletecom', id=com[7]) }}">{{ _('Удалить') }}</a>
                    {% if com[17] == current_user.login or current_user.login == 'tehno-09@mail.ru' %}
                    <span>{{ '   ' }}</span><a href="{{ url_for('main.edit_com', id=com[7]) }}">{{ _('Редактировать') }}</a>
                    {% endif %}
                {% endif %}
            </td>
        </tr>
    </table>

app/templates/_post.html
{{ moment.include_moment() }}
{{ moment.include_jquery() }}
{{ moment.lang("ru") }}
    <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="sp-feature-box-3 margin-bottom">
              <div class="img-box"> <a href="{{ url_for('main.item_fw', id=item[0]) }}" class="view-btn uppercase">View</a>
                <img src="{{ item[10][0] }}" alt="" class="img-responsive"/> </div>
            <div class="clearfix"></div>
            <br/>
            <h5 class="less-mar-1">{{ item[4] }}</h5>
            <p>{{ item[5] }}</p>
            <div>
                <del class="oldprice">{{ item[6] }}</del>
                <span class="productprice">{{ item[7] }}</span>
                <span class="discountitem">({{ item[3] }} % off)</span>
            </div>
            <br/>
            <a class="btn btn-border light btn-small" href="{{ item[2] }}" target="_blank">Link</a> </div>
            <br/>
    </div>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Social Network{% else %}{{ _('Добро пожаловать в Социальную сеть') }}{% endif %}
{% endblock %}

{% block navbar %}
    <div id="navlist">
        <a href="#">Home</a>
        <a href="#">Our Products</a>
        <a href="#">Careers</a>
        <a href="#">About Us</a>
        <a href="#">Contact Us</a>

        <!-- seach bar right align -->
        <div class="app-header-search__input-container">
            <input type="search" class="app-header-search__input" autocomplete="off" autocorrect="off">
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/edit_post.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Редактирование комментария') }}</h1>
        <div class="row">
            <div class="col-md-4">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <script>
    window.onload = function()
    {
        let SelVUZ = document.getElementById('SelVUZ');
        SelVUZ.onchange = function() {
            document.querySelector("input[id*='submit']").click()
            updateLeafData();
        }
        let SelFack = document.getElementById('SelFack');
        SelFack.onchange = function() {
            document.querySelector("input[id*='submit']").click()
            updateLeafData();
        }
    }
    </script>
    <h1>{{ _('Редактирование профиля') }}</h1>
        <div class="row">
            <div class="col-md-4">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
{% endblock %}

app/templates/foloww.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
<table class="table table-hover">
        {% if friendempty == True and current_user.login != login %}
            <p>{{ _('У пользователя еще нет фолловеров, будьте первым') }} <br> <a href="{{ url_for('main.follow', id=idfoll) }}">{{ _('Follow') }}</a></p>
        {% endif %}
        {% if friendempty == True and current_user.login == login %}
            <p>{{ _('У вас нет друзей') }} <br> <a href="{{ url_for('main.user', id=id) }}">{{ _('Вернуться') }}</a> </p>
        {% endif %}
        {% for frend in frendi %}
        <tr>
            <td width="100px">
                <a href="{{ url_for('main.user', id = frend[7]) }}">
                    <img src="{{ frend[11] }}" width="100" height="100"/>
                </a>
            </td>
            <td width="100">
                {% set user_link %}
                    <span class="user_popup">
                        <a href="{{ url_for('main.user', id=frend[7]) }}">
                            {{ frend[3] }}
                        </a>
                    </span>
                {% endset %}
            </td>
        </tr>
            <th width="100" align="center">
                    {{ _('%(username)s',
                    username=user_link) }}
                <br/>
            </th>
        {% endfor %}
    </table>

app/templates/sendcom.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Напишите свой комментарий') }}</h1>
        <div class="row">
            <div class="col-md-4">
                {{ wtf.quick_form(forma) }}
            </div>
        </div>
{% endblock %}

app/templates/unfoloww.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
<table class="table table-hover">
        {% if friendempty == True %}
            <p>{{ _('Пользователь еще ни на кого не подписан') }}  <br> <a href="{{ url_for('main.user', id=id) }}">{{ _('Вернуться') }}</a> </p>
        {% endif %}
        <tr>
            {% for frend in frendi %}
            <td width="100px">
                <a href="{{ url_for('main.user', id = frend[7]) }}">
                    <img src="{{ frend[11] }}" width="100" height="100"/>
                </a>
            </td>
            <td width="100">
                {% set user_link %}
                    <span class="user_popup">
                        <a href="{{ url_for('main.user', id=frend[7]) }}">
                            {{ frend[3] }}
                        </a>
                    </span>
                {% endset %}
            </td>
        </tr>
        <tr>
            <td width="100">
                    {{ _('%(username)s',
                    username=user_link) }}
            </td>
        </tr>
        {% endfor %}
    </table>

app/templates/user.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
    {{ pagination.links }}
    <table class="table table-hover">
        <tr>
            <td width="200"><a href="{{ url_for('main.user_popup', id = id) }}"><img src="{{ avatar }}" width="200" height="200"></a></td>
            <td>
                <h1>{{ fio }}</h1>
                {% if current_user.login == 'tehno-09@mail.ru' and current_user.login != logen  %}
                    <p><a href="{{ url_for('main.delete_profile', id=id) }}">{{ _('Удалить из жизни') }}</a></p>
                {% endif %}
                {% if about_me %}<p>{{ about_me }}</p>{% endif %}
                <p><a href="{{ url_for('main.foloww', id=id) }}">{{ _('%(count)s followers', count=followers) }}</a>, <a href="{{ url_for('main.folowww', id=id) }}">{{ _('%(count)s following', count=following) }}</a></p>
                {% if logen == current_user.login %}
                <p><a href="{{ url_for('main.edit_profile') }}">{{ _('Edit your profile') }}</a></p>
                {% else %}
                    {% if followed == False %}
                    <p><a href="{{ url_for('main.follow', id=id) }}">{{ _('Follow') }}</a></p>
                    {% else %}
                    <p><a href="{{ url_for('main.unfollow', id=id) }}">{{ _('Unfollow') }}</a></p>
                    {% endif %}
                {% endif %}
            </td>
        </tr>
    </table>
    <b><p>{{ _('Напишите пользователю что-нибудь:' )}}</p></b>
    {% if form %}
    {{ wtf.quick_form(form) }}
    <br>
    {% endif %}
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    {{ pagination.links }}
{% endblock %}

app/templates/user_popup.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
<table class="table table-hover">
        <tr>
            <td width="500"><img src="{{ avatar }}" width="500" height="500"></td>
            <div class="col-md-4">
            <td>
                <h1>{{ fio }}</h1>
                {% if about_me %}<p>{{ _('Статус: %(about_me)s', about_me=about_me) }}</p>{% endif %}
                {% if phone %}<p>{{ _('Телефон: %(phone)s', phone=phone) }}</p>{% endif %}
                {% if gender %}<p>{{ _('Пол: %(gender)s', gender=gender) }}</p>{% endif %}
                {% if dr %}<p>{{ _('День рождения: %(dr)s', dr=dr) }}</p>{% endif %}
                {% if vuz %}<p>{{ _('ВУЗ: %(vuz)s', vuz=vuz) }}</p>{% endif %}
                {% if facultet %}<p>{{ _('Факультет: %(facultet)s', facultet=facultet) }}</p>{% endif %}
                {% if kafedra %}<p>{{ _('Кафедра: %(kafedra)s', kafedra=kafedra) }}</p>{% endif %}
                <p>{{ _('%(count)s followers', count=followers) }}, {{ _('%(count)s following', count=following) }}</p>
                <p><a href="{{ url_for('main.user', id=iduser) }}">{{ _('Вернуться') }}</a></p>
            </td>
            </div>
        </tr>
    </table>